/**
 * Thurin contract ABIs
 * Generated from contracts/src/ — must match deployed Solidity contracts
 */

export const THURIN_SBT_ABI = [
  {
    type: 'constructor',
    inputs: [
      { name: '_honkVerifier', type: 'address' },
      { name: '_priceFeed', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  // Constants
  {
    type: 'function',
    name: 'MINT_POINTS',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'REFERRAL_POINTS',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PROOF_DATE_TOLERANCE_DAYS',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MIN_VALIDITY_PERIOD',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PRICE_STALENESS_THRESHOLD',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  // State variables
  {
    type: 'function',
    name: 'honkVerifier',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'priceFeed',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'mintPriceUSD',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'renewalPriceUSD',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'validityPeriod',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  // Mappings
  {
    type: 'function',
    name: 'tokenMintTimestamp',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'userTokenId',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nullifierUsed',
    inputs: [{ name: 'nullifier', type: 'bytes32' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenNullifier',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'trustedIACARoots',
    inputs: [{ name: 'root', type: 'bytes32' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'iacaStateNames',
    inputs: [{ name: 'root', type: 'bytes32' }],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'referralCount',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'referredBy',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'points',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  // ERC721 functions
  {
    type: 'function',
    name: 'name',
    inputs: [],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'symbol',
    inputs: [],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'balanceOf',
    inputs: [{ name: 'owner', type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ownerOf',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenURI',
    inputs: [{ name: 'tokenId', type: 'uint256' }],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  // Core functions
  {
    type: 'function',
    name: 'mint',
    inputs: [
      { name: 'proof', type: 'bytes' },
      { name: 'nullifier', type: 'bytes32' },
      { name: 'addressBinding', type: 'bytes32' },
      { name: 'proofDate', type: 'uint32' },
      { name: 'eventId', type: 'bytes32' },
      { name: 'iacaRoot', type: 'bytes32' },
      { name: 'proveAgeOver21', type: 'bool' },
      { name: 'proveAgeOver18', type: 'bool' },
      { name: 'proveState', type: 'bool' },
      { name: 'provenState', type: 'bytes2' },
      { name: 'referrerTokenId', type: 'uint256' },
    ],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'renew',
    inputs: [
      { name: 'proof', type: 'bytes' },
      { name: 'nullifier', type: 'bytes32' },
      { name: 'addressBinding', type: 'bytes32' },
      { name: 'proofDate', type: 'uint32' },
      { name: 'eventId', type: 'bytes32' },
      { name: 'iacaRoot', type: 'bytes32' },
      { name: 'proveAgeOver21', type: 'bool' },
      { name: 'proveAgeOver18', type: 'bool' },
      { name: 'proveState', type: 'bool' },
      { name: 'provenState', type: 'bytes2' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'burn',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'isValid',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getExpiry',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getMintPrice',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getRenewalPrice',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getETHPrice',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalSupply',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  // Admin functions
  {
    type: 'function',
    name: 'addIACARoot',
    inputs: [
      { name: 'root', type: 'bytes32' },
      { name: 'stateName', type: 'string' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'removeIACARoot',
    inputs: [{ name: 'root', type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setMintPriceUSD',
    inputs: [{ name: '_mintPriceUSD', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setRenewalPriceUSD',
    inputs: [{ name: '_renewalPriceUSD', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setValidityPeriod',
    inputs: [{ name: '_validityPeriod', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdraw',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  // Events
  {
    type: 'event',
    name: 'Minted',
    inputs: [
      { name: 'user', type: 'address', indexed: true },
      { name: 'tokenId', type: 'uint256', indexed: true },
      { name: 'referrerTokenId', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'Renewed',
    inputs: [
      { name: 'user', type: 'address', indexed: true },
      { name: 'tokenId', type: 'uint256', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'Burned',
    inputs: [
      { name: 'user', type: 'address', indexed: true },
      { name: 'tokenId', type: 'uint256', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'IACARootAdded',
    inputs: [
      { name: 'root', type: 'bytes32', indexed: true },
      { name: 'stateName', type: 'string', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'IACARootRemoved',
    inputs: [{ name: 'root', type: 'bytes32', indexed: true }],
  },
  {
    type: 'event',
    name: 'MintPriceUpdated',
    inputs: [
      { name: 'oldPriceUSD', type: 'uint256', indexed: false },
      { name: 'newPriceUSD', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'RenewalPriceUpdated',
    inputs: [
      { name: 'oldPriceUSD', type: 'uint256', indexed: false },
      { name: 'newPriceUSD', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'ValidityPeriodUpdated',
    inputs: [
      { name: 'oldPeriod', type: 'uint256', indexed: false },
      { name: 'newPeriod', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'Transfer',
    inputs: [
      { name: 'from', type: 'address', indexed: true },
      { name: 'to', type: 'address', indexed: true },
      { name: 'tokenId', type: 'uint256', indexed: true },
    ],
  },
  // Errors
  { type: 'error', name: 'ProofDateFromFuture', inputs: [] },
  { type: 'error', name: 'ProofDateTooOld', inputs: [] },
  { type: 'error', name: 'UntrustedIACA', inputs: [] },
  { type: 'error', name: 'NullifierAlreadyUsed', inputs: [] },
  { type: 'error', name: 'InvalidProof', inputs: [] },
  { type: 'error', name: 'AlreadyHasSBT', inputs: [] },
  { type: 'error', name: 'InsufficientPayment', inputs: [] },
  { type: 'error', name: 'InvalidValidityPeriod', inputs: [] },
  { type: 'error', name: 'Soulbound', inputs: [] },
  { type: 'error', name: 'WithdrawFailed', inputs: [] },
  { type: 'error', name: 'NoSBTToRenew', inputs: [] },
  { type: 'error', name: 'NoSBTToBurn', inputs: [] },
  { type: 'error', name: 'StalePrice', inputs: [] },
  { type: 'error', name: 'InvalidPrice', inputs: [] },
  { type: 'error', name: 'Unauthorized', inputs: [] },
] as const;

export const THURIN_VERIFIER_ABI = [
  {
    type: 'constructor',
    inputs: [
      { name: '_honkVerifier', type: 'address' },
      { name: '_sbt', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'PROOF_DATE_TOLERANCE_DAYS',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'dappVerificationCount',
    inputs: [{ name: 'dapp', type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getSBTExpiry',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasValidSBT',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'honkVerifier',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'sbt',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'verify',
    inputs: [
      { name: 'user', type: 'address' },
      { name: 'proof', type: 'bytes' },
      { name: 'nullifier', type: 'bytes32' },
      { name: 'addressBinding', type: 'bytes32' },
      { name: 'proofDate', type: 'uint32' },
      { name: 'eventId', type: 'bytes32' },
      { name: 'iacaRoot', type: 'bytes32' },
      { name: 'proveAgeOver21', type: 'bool' },
      { name: 'proveAgeOver18', type: 'bool' },
      { name: 'proveState', type: 'bool' },
      { name: 'provenState', type: 'bytes2' },
    ],
    outputs: [{ type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  { type: 'error', name: 'NoValidSBT', inputs: [] },
  { type: 'error', name: 'ProofDateFromFuture', inputs: [] },
  { type: 'error', name: 'ProofDateTooOld', inputs: [] },
  { type: 'error', name: 'InvalidProof', inputs: [] },
] as const;

export const THURIN_POINTS_ABI = [
  {
    type: 'constructor',
    inputs: [
      { name: '_sbt', type: 'address' },
      { name: '_verifier', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'POINTS_PER_VERIFICATION',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'claimDappPoints',
    inputs: [{ name: 'dapp', type: 'address' }],
    outputs: [{ name: 'claimed', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimedVerifications',
    inputs: [{ name: 'dapp', type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'dappName',
    inputs: [{ name: 'dapp', type: 'address' }],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'dappPoints',
    inputs: [{ name: 'dapp', type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'dappRegistered',
    inputs: [{ name: 'dapp', type: 'address' }],
    outputs: [{ type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getDappInfo',
    inputs: [{ name: 'dapp', type: 'address' }],
    outputs: [
      { name: 'name', type: 'string' },
      { name: 'points', type: 'uint256' },
      { name: 'verifications', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getTopDapps',
    inputs: [{ name: 'limit', type: 'uint256' }],
    outputs: [
      { name: 'dapps', type: 'address[]' },
      { name: 'verifications', type: 'uint256[]' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'hasValidSBT',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ name: 'valid', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingDappPoints',
    inputs: [{ name: 'dapp', type: 'address' }],
    outputs: [{ name: 'pending', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'registerDapp',
    inputs: [{ name: 'name', type: 'string' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'registeredDappCount',
    inputs: [],
    outputs: [{ name: 'count', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'registeredDapps',
    inputs: [{ name: 'index', type: 'uint256' }],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'sbt',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalDappPoints',
    inputs: [{ name: 'dapp', type: 'address' }],
    outputs: [{ name: 'total', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'userPoints',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [{ name: 'points', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'verifier',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'DappPointsClaimed',
    inputs: [
      { name: 'dapp', type: 'address', indexed: true },
      { name: 'points', type: 'uint256', indexed: false },
      { name: 'totalVerifications', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'DappRegistered',
    inputs: [
      { name: 'dapp', type: 'address', indexed: true },
      { name: 'name', type: 'string', indexed: false },
    ],
  },
  { type: 'error', name: 'AlreadyRegistered', inputs: [] },
  { type: 'error', name: 'NothingToClaim', inputs: [] },
  { type: 'error', name: 'Unauthorized', inputs: [] },
] as const;
